### ISSUE TITLE
Using Causallift for later predition

### ISSUE THREAD

**Issue by Jami1141** [Minyus/causallift#10]
I would like to ask you a question related to using Causallift for later prediction.
I am using A/B test data for training the code. To do that foe example my data is "df". Then I split them to train and test set and I get uplift scores for each individual.
Suppose that I need to use this code for prediction using new data and calculate uplift scores for new data using the trained model.
In this case, all the parameters of XGBoost that I used for training should be the same when I use new data? 
Second is that when I use new data, then new data will be test set and train would be data used for training the code?
Is it work like this? If we use like this then new data will see exactly the trained code as before right?
Thanks in advance,

**Comment by Jami1141** [comment]
Since I use A/B test data for training, I set enable_ipw to False. But when I want to do prediction for new data I should to set it to True? Is it fine since for model I set it to False and I do not have propensity values?

**Comment by Minyus** [comment]
I added explanation in the following sections in README.md.

https://github.com/Minyus/causallift#how-causallift-works
https://github.com/Minyus/causallift#how-to-run-inferrence-prediction-of-cate-for-new-data-with-treatment-and-outcome-unknown

`enable_ipw` flag is used only during training.

**Comment by Jami1141** [comment]
I tried to split train data as my data for train model and test data as my new data. First it does not accept without Treatment and Outcome. I have to add two features for new data but as you suggested all 0. But in the step:  
 train_df,test_df = cl.estimate_cate_by_2models()
it makes error:
Only one class presents in Y_true. ROC AUC score is not defined in that case

**Comment by Jami1141** [comment]
In 
https://github.com/Minyus/causallift#how-to-run-inferrence-prediction-of-cate-for-new-data-with-treatment-and-outcome-unknown

is mentioned that CATE is calculated from Trained data. It means that we have treated and untreated models for only trained data as I understood from your plot.
But why when I add a feature named Outcome and Treatment to Test data (which is new data now) with all 0 it makes errors saying that ROC AUC score can not be defined since for Outcome we have only one class. If only trained data are split to two models of treated and untraeted then why we should have error for test data.
This I do not understand.

**Comment by Jami1141** [comment]
I have another question. If train data and test data have different number of features code makes errors? Should train and test data have the same number of features?

**Comment by Minyus** [comment]
The error "Only one class presents in Y_true. ROC AUC score is not defined in that case"
comes from the evaluation step after predicting CATE.
To avoid the error, you can set Treatment and Outcome for test_df to random (half samples to 0, half samples to 1).

CATE for test_df is calculated from the 2 models trained with train_df.
Treatment and Outcome for test_df are not used for prediction of CATE, but used for evaluation.

**Comment by Minyus** [comment]
`train_df` and `test_df` need to have the same number of features. Otherwise, an error should be raised.

**Comment by Jami1141** [comment]
Thank you for the respond!

**Comment by Jami1141** [comment]
If some features have all their values 0 code makes error?
Because when I add three features to the test data (new data) with all values to 0 to have the same number of features with train data. I gets error:


[Estimate propensity scores for Inverse Probability Weighting.]
number of positives:  228
number of negatives:  7495
scale_pos_weight:  32.87280701754386
[2020-03-25 14:43:18,709|causallift.context.flexible_context|INFO] Run pipeline (tags: ['011_bundle_train_and_test_data'], SequentialRunner, only_missing: False)
[2020-03-25 14:43:18,723|kedro.pipeline.node|INFO] Running node: bundle_train_and_test_data([args_raw,test_df,train_df]) -> [df_00]
[2020-03-25 14:43:18,724|kedro.pipeline.node|ERROR] Node `bundle_train_and_test_data([args_raw,test_df,train_df]) -> [df_00]` failed with error: 
[2020-03-25 14:43:18,729|kedro.runner.sequential_runner|WARNING] There are 1 nodes that have not run.
You can resume the pipeline run by adding the following argument to your previous command:

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-29-80924613c0b0> in <module>()
     20 uplift_model_params={'cv': 3, 'estimator': 'xgboost.XGBClassifier', 'n_jobs': -1, 'param_grid': {'base_score': [0.5], 'booster': ['gbtree'], 'colsample_bylevel': [1], 'colsample_bytree': [1], 'gamma': [0], 'learning_rate': [0.1], 'max_delta_step': [0], 'max_depth': [3], 'min_child_weight': [1], 'missing': [None], 'n_estimators': [100], 'n_jobs': [-1], 'nthread': [None], 'objective': ['binary:logistic'], 'random_state': [0], 'reg_alpha': [0], 'reg_lambda': [1], 'subsample': [1], 'verbose': [0]}, 'return_train_score': False, 'scoring': None, 'search_cv': 'sklearn.model_selection.GridSearchCV'}
     21 uplift_model_params.update({'scale_pos_weight': [scale_pos_weight]})
---> 22 cl = CausalLift(train_df, test_df, enable_ipw=False, verbose=3, uplift_model_params=uplift_model_params)

**Comment by Minyus** [comment]
It should be fine that some features for all the samples are all 0. 
Could you share the screenshot of the error because I cannot find where the error is raised in your post?

**Comment by Jami1141** [comment]
<img width="516" alt="error" src="https://user-images.githubusercontent.com/62301816/77559172-201e8700-6ebc-11ea-81a5-2ac95f4c6bf5.png">

**Comment by Jami1141** [comment]
This is the same kind of error that get when I had different features in test and train set

**Comment by Jami1141** [comment]
I solved this error. There was a problem in my features. But now I have another error:
When I use scale_pos_weight the same way that you proposed me it complains. I attach the way I used Scale_pos_weight.
I removed it from XGBoost parameters as you did it in your example.
<img width="643" alt="scale" src="https://user-images.githubusercontent.com/62301816/77563070-13e8f880-6ec1-11ea-8739-eec6b4d00f86.png">
<img width="619" alt="error2" src="https://user-images.githubusercontent.com/62301816/77563079-18151600-6ec1-11ea-9fc1-f45db96098d8.png">

**Comment by Jami1141** [comment]
Code works when I use scale_pos_weight as it was in the XGBoost parameter as a number like: 30
But when I use above method for scale_pos_weight it does not work.

**Comment by Jami1141** [comment]
Apart from the question above, I see that two models for treated and untreated uses tested data as well? right? at least I see it when code runes
<img width="633" alt="run" src="https://user-images.githubusercontent.com/62301816/77567544-983e7a00-6ec7-11ea-8a33-f8d7e967d2e8.png">

**Comment by Minyus** [comment]
I need to see the entire error message. Could you upload your Jupyter notebook file?

The 2 models for treated and untreated are trained using train_df and used to predict CATE for both train_df and test_df and then metrics (accuracy, precision, recall, f1, ROC_AUC) are computed.

**Comment by Jami1141** [comment]
Apparently by mistake I closed the issue :(
Is it possible to re do it?
For all errors I don't know how to save notebook including errors in a file
to upload it in Github.
Can you help me? I searched but I did not find if errors also will be saved
or not.

You said: The 2 models for treated and untreated are trained using train_df
and used to predict CATE for both train_df and test_df and then metrics
(accuracy, precision, recall, f1, ROC_AUC) are computed
But I see that for treated and untreated models the total numbers of
trained and test for each model is equal to my test (new data) set not
train set. I have 7723 test set and 8755 test set.

**Comment by Minyus** [comment]
Error output will be saved with your code in Jupyter notebooks. 

> for treated and untreated models the total numbers of
trained and test for each model is equal to my test (new data) set not
train set. 

Let me check your Jupyter notebook.

**Comment by Minyus** [comment]
To avoid the error `Only one class presents in Y_true. ROC AUC score is not defined in that case`, I released CausalLift version 1.0.2.

**Comment by Jami1141** [comment]
Hello again,

I have attached a pdf of my jupyter notebook.
My trained data (used for training old data) have 7723 rows and test data
(new data) has 8755 rows.
The first pdf file includes the error I get when I use scale_pos_weight as
you suggested.
The second pdf file is when I use only a number for scale_pos_weight like:
32 and you see two models of treated and untreated. I have questions that
which data will be taken for creating these two models? if trained data
only why  for example in treated model (Outcome estimated by the model
trained using samples with observational Treatment: 1.0) in total for train
and test I have 3866 + 4308? what is 3866 and 4308? Should not be here the
train and test set of number of treated people only?

**Comment by Minyus** [comment]
I don't see any attachment in your post.
You can upload your Jupyter notebook to your GitHub repository.
Here is how: 
https://medium.com/@sauravbhagat_10426/how-to-upload-code-to-github-6db1c8ff56aa

**Comment by Minyus** [comment]
Your 7723 train samples seem to include 3857 untreated samples (which were used to train the model for untreated) and 3866 treated samples (which were used to train the model for treated).
Your 8755 test samples seem to include 4447 untreated samples and 4308 treated samples.

**Comment by Minyus** [comment]
I found a problem in the code I posted to use `scale_pos_weight`. 
Here is the fixed version:

```python
n_positives = len(train_df.query("Outcome == 1"))
print("number of positives: ", n_positives)

n_negatives = len(train_df.query("Outcome == 0"))
print("number of negatives: ", n_negatives)

scale_pos_weight = n_negatives / n_positives
print("scale_pos_weight: ", scale_pos_weight)

# Reference: https://xgboost.readthedocs.io/en/latest/parameter.html

uplift_model_params={'cv': 3, 'estimator': 'xgboost.XGBClassifier', 'n_jobs': -1, 'return_train_score': False, 'scoring': None, 'search_cv': 'sklearn.model_selection.GridSearchCV'}
param_grid = {'base_score': [0.5], 'booster': ['gbtree'], 'colsample_bylevel': [1], 'colsample_bytree': [1], 'gamma': [0], 'learning_rate': [0.1], 'max_delta_step': [0], 'max_depth': [3], 'min_child_weight': [1], 'missing': [None], 'n_estimators': [100], 'n_jobs': [-1], 'nthread': [None], 'objective': ['binary:logistic'], 'random_state': [0], 'reg_alpha': [0], 'reg_lambda': [1], 'subsample': [1], 'verbose': [0]}
param_grid.update({'scale_pos_weight': [scale_pos_weight]})
uplift_model_params.update({'param_grid': param_grid})
cl = CausalLift(train_df, test_df, enable_ipw=False, verbose=3, uplift_model_params=uplift_model_params)
```
