### ISSUE TITLE
Generated data are random data?

### ISSUE THREAD

**Issue by Jami1141** [Minyus/causallift#11]
I have a question about the generated data in one part of your code. I would like to know are they random data? I want to use random data to apply to the code and see how results of CATE varies compared to my data.

Thanks in advance

**Comment by Minyus** [comment]
Yes, the generated data is random data based on parameters.
For more details, please see the comments in the code:

https://github.com/Minyus/causallift/blob/develop/src/causallift/generate_data.py

**Comment by Jami1141** [comment]
Thanks for your reply. Do we need to generate propensity feature for this generated data?

**Comment by Minyus** [comment]
It depends.
If you want to use simulated data for observational data, `propensity_coef` can be used.
If you want to use simulated data for A/B Test (Randomized Controlled Trial), `propensity_coef` is not needed.
