### ISSUE TITLE
Order of features in train and new data

### ISSUE THREAD

**Issue by Jami1141** [Minyus/causallift#12]
I have a question. Is it necessary to have the same order for features in train and new data set?

**Comment by Minyus** [comment]
Do you mean the order of feature columns in each of the pandas data frame? If so, it doesn't matter because column names are used.

**Comment by Jami1141** [comment]
So it depend If I use dataframe as train or numpy array yes? in our case since we are using dataframe is fine but If we have numpy array we have to reorder them right?

**Comment by Minyus** [comment]
numpy array input should raise an error.

**Comment by Minyus** [comment]
pandas dataframes are chosen to avoid column order issues.

**Comment by Jami1141** [comment]
Ok great!
