### ISSUE TITLE
Is there a causal modeling for multiple treatments? 

### ISSUE THREAD

**Issue by Jami1141** [Minyus/causallift#14]
I am asking this issue here, since Causallift handle binary treatment. Do you know a python code that  compare multiple treatments and give the uplift for each individual to be able to compare treatments?
Do you know such a code or do you plan to develop a code for this case?

Thnaks

**Comment by Minyus** [comment]
I haven't seen a Python implementation that can handle non-binary treatment values.
I'm not sure how to handle non-binary treatment values and do not plan to add the feature to CausalLift.
Any contributions, such as sharing some papers or pull requests if you could implement, are welcome.

**Comment by Jami1141** [comment]
If we use 2 different treatment binaries and use causallift independently for a binary treatment which includes treatment 1 and no treatment and another binary which includes treatment 2 and no treatment. Then can we compare uplifts obtained from two different results?

**Comment by Minyus** [comment]
I think so.

**Comment by Jami1141** [comment]
So, we can compare uplifts scores for two different set of binary treatment. In this case, it is very good point. For example if for first binary treatment (0,1) for student 1 uplift is 0.2 and for second set of treatment binary(0,2) for student 1 uplift is 0.5, it means that treatment 2 is recommended to this student. yes?

**Comment by Minyus** [comment]
Yes.
