### ISSUE TITLE
Error regarding to base_score

### ISSUE THREAD

**Issue by Jami1141** [Minyus/causallift#18]
Thanks for your very nice written code. I tried to use your code using my dataset. In the step:

train_df, test_df = cl.estimate_cate_by_2_models()
print('\n[Show CATE for train dataset]')
train_df.to_csv('CATE_for_Train.csv')
test_df.to_csv('CATE_for_Test.csv')

print('\n[Estimate the effect of recommendation based on the uplift model]')
estimated_effect_df = cl.estimate_recommendation_impact()
#df.to_csv('df.csv')
print('\n[Show the estimated effect of recommendation based on the uplift model]')
display(estimated_effect_df)

I have following error:

![Screenshot 2020-08-26 at 17 56 47](https://user-images.githubusercontent.com/62301816/91327322-a6215f80-e7c5-11ea-85f4-77b3a2b1852e.png)
![Screenshot 2020-08-26 at 17 57 13](https://user-images.githubusercontent.com/62301816/91327343-ade10400-e7c5-11ea-83f6-e3a115775180.png)

Which is related to base score. But I have already defined base score in Uplift_model_param.
May I ask you what could be the problem?

Thanks in advance

**Comment by Minyus** [comment]
CausalLift may not work with scikit-learn 0.22 or later. Could you try scikit-learn 0.21.3?

pip install scikit-learn==0.21.3

**Comment by Jami1141** [comment]
Thank you so much. Indeed it was scikit-learn version problem!
