### ISSUE TITLE
How do we can give separtae scale_pos_weight for two separated models? 

### ISSUE THREAD

**Issue by Jami1141** [Minyus/causallift#19]
In the causalfit, at the beginning of the code, we can set scal_pos_weight but not for each model separately. Since I have high imbalance data and each model for each treatment I could have different scale_pos_weight, I must set it for each model. At the beginning of the code, we split data to train_df and test_df but all data regardless of treatment. This is done only for our later simulation. But where two models gets separated? in this case I can model (XGBoost) for each treatment and I can specify separate scale_pos_weight.

I am asking this because when I use two separated models for two treatment by myself and I specify a separated scale_pos_weight, then results with causallift is different.

Thanks in adavnce

**Comment by Minyus** [comment]
2 model objects are constructed (initialized) using the same hyperparameters, and then trained using treated samples and untreated samples respectively. CausalLift does not support to use different hyperparameters for the 2 models by design.
