### ISSUE TITLE
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

### ISSUE THREAD

**Issue by arsine1996** [Minyus/causallift#21]
Hi, thank you for the great package, it is very great and useful. I'm having some troubles implementing the code, can you please have a look.
In my original data I did not have any NAs or missing values, but when run the code I get the following error.

`cl = CausalLift(X0, X11, enable_ipw=True, verbose=3)`
```

[[2021-01-14 15:07:57,554|causallift.nodes.estimate_propensity|INFO] 
### Confusion Matrix for Test:
[2021-01-14 15:07:57,559|kedro.pipeline.node|ERROR] Node `estimate_propensity([args,df_00,propensity_model]) -> [df_01]` failed with error: 
Input contains NaN, infinity or a value too large for dtype('float64').
[2021-01-14 15:07:57,564|kedro.runner.sequential_runner|WARNING] There are 1 nodes that have not run.
You can resume the pipeline run by adding the following argument to your previous command:]

.......

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
```

**Comment by Minyus** [comment]
Hi @arsine1996 ,

Recent versions of Python packages may not work.
I would suggest you try old versions, for example:

`pip install 'kedro==0.15.9' 'scikit-learn<0.22' 'pipelinex==0.2.3'`

**Comment by arsine1996** [comment]
Thanks for the suggestion, actually I had all of this requirements, but still have the same error. Maybe the issue is with my data, because your sample example works.
