### ISSUE TITLE
TypeError: run() missing 1 required positional argument: 'hook_manager'

### ISSUE THREAD

**Issue by ya-stack** [Minyus/causallift#22]
Hi Team,

I am getting a **TypeError: run() missing 1 required positional argument: 'hook_manager'** while executing CausalLift(train_df, test_df, enable_ipw=True, verbose=3). For your reference, please find attached the snippet of dataset.
<img width="966" alt="image" src="https://user-images.githubusercontent.com/56586780/163855622-936a3f51-fb6c-4164-ac78-1ba810354155.png">

**Comment by Minyus** [comment]
Hi @ya-stack ,

This package may not work with recent versions of the dependent packages.
Could you try installing old versions as follows?

```bash
pip install 'kedro==0.17.7' 'scikit-learn<0.22'
```
or 
```bash
pip install 'kedro==0.15.9' 'scikit-learn<0.22'
```

**Comment by ya-stack** [comment]
Yes it worked, thanks a lot!
