### ISSUE TITLE
The effect of Stratify = ['Treatment']

### ISSUE THREAD

**Issue by Jami1141** [Minyus/causallift#8]
I have a question regarding to Stratify = ['Treatment'].
What is it for? Is it necessary to add it to the line of code?

Thanks in advance,

**Comment by Minyus** [comment]
You can find explanation of `stratify` of `sklearn.model_selection.train_test_split` at:

https://stackoverflow.com/a/38889389/12236180

It is used to make sure the proportion of `Treatment` is almost the same for `train_df` and `test_df`.

**Comment by Jami1141** [comment]
Ok thanks. But without stratify also works.

**Comment by Minyus** [comment]
Yes, `sklearn.model_selection.train_test_split` without `stratify` usually works fine.
