### ISSUE TITLE
A clear explanation

### ISSUE THREAD

**Issue by Jami1141** [Minyus/causallift#9]
I would like to ask you to please explain in details what Causallift does.
I think it first model treated and non treated samples separately. In this case for each model we have conversion rates for each individual. Then after I do not know what happens and why we do simulation and how? how exactly uplifts are calculated?
I want to clearly understand it since I choosed Causalift for my project.

Thanks in advance

**Comment by Minyus** [comment]
I added explanation in the following sections in README.md.

https://github.com/Minyus/causallift#how-causallift-works
https://github.com/Minyus/causallift#how-to-run-inferrence-prediction-of-cate-for-new-data-with-treatment-and-outcome-unknown

Hope it's clear.

The purpose of Uplift Modeling is to estimate CATE. Conversion rates for each individual are computed in the process. (CATE = `Conversion rate if treated` - `Conversion rate if not treated`.)

Evaluation by simulation is to estimate the impact of following the recommendation by CATE (Treat only if CATE is high). If you do not find simulation useful, you can skip it.
